apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  config.yaml: |-
    apiUrl: "https://my.api.com/api/v1"
    username: {{username}} # replace with sed -i 's/{{username}}/admin/g' sample-secrets-2.yml
    password: {{password}} # replace with sed -i 's/{{password}}/pass/g' sample-secrets-2.yml
