apiVersion: v1
kind: Pod
metadata:
  name: my-app-prod
  labels:
    app: my-app
    type: frontend
spec:
  containers:
  - name: my-container
    image: redis
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
  restartPolicy: Never
