apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secrets
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_USER: YWRtaW4= # echo -n 'admin' | base64
  MYSQL_ROOT_PASSWORD: d3AtbXlzcWwtcGFzc3dvcmQ= # echo -n "wp-mysql-password" | base64
