apiVersion: v1
kind: Pod
metadata:
  name: my-app-prod
  labels:
    app: my-app
    type: frontend
spec:
  containers:
  - name: my-container
    image: redis
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: special-config
          key: log_level
  restartPolicy: Never
